print("Iniciando Conversa em Python - UFRPE")
print("Qual o seu nome?")
nome = input()
print("Qual dia você nasceu?")
dia = input()
print("Qual mês você nasceu?")
mes = input()
print("-----------------------------")
print("Olá, " + nome + " seu aniversário é no dia " + dia + " de " + mes)